# Generated by Django 5.1.3 on 2024-12-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_state'),
        ('student', '0003_remove_student_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(related_name='schools', to='student.student', verbose_name='Alumnos asignados'),
        ),
    ]
