# Generated by Django 5.1.3 on 2024-12-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_schools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='schools',
        ),
    ]
