# Generated by Django 5.1.3 on 2024-12-10 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0003_school_students'),
        ('student', '0003_remove_student_schools'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school', verbose_name='Escuela')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Alumno')),
            ],
            options={
                'verbose_name': 'Asignación de Escuela',
                'verbose_name_plural': 'Asignaciones de Escuelas',
                'unique_together': {('school', 'student')},
            },
        ),
    ]
